const PDFDocument = require('pdfkit');
const pool = require('../db');

const generateStudentReportCard = async (req, res, next) => {
  try {
    const studentRes = await pool.query(`
      SELECT s.*, st.name as stream_name FROM students s
      LEFT JOIN streams st ON s.stream_id = st.id
      WHERE s.id = $1
    `, [req.params.studentId]);

    if (!studentRes.rows.length) return res.status(404).json({ error: 'Student not found' });
    const student = studentRes.rows[0];

    const scoresRes = await pool.query(`
      SELECT sc.*, su.name as subject_name, su.code,
        g.grade, g.remark
      FROM scores sc
      JOIN subjects su ON sc.subject_id = su.id
      LEFT JOIN grading_scale g ON sc.total_score BETWEEN g.min_score AND g.max_score
      WHERE sc.student_id = $1
      ORDER BY su.name
    `, [req.params.studentId]);

    const scores = scoresRes.rows;
    const total = scores.reduce((sum, s) => sum + parseFloat(s.total_score), 0);
    const average = scores.length ? (total / scores.length).toFixed(2) : 0;

    const posRes = await pool.query(`
      SELECT student_id, SUM(total_score) as total
      FROM scores WHERE term = $1 AND academic_year = $2
      GROUP BY student_id ORDER BY total DESC
    `, [scores[0]?.term || 'Term 1', scores[0]?.academic_year || '2025']);

    const position = posRes.rows.findIndex(r => r.student_id === student.id) + 1;

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=report_${student.admission_number}.pdf`);
    doc.pipe(res);

    // Header
    doc.rect(0, 0, 595, 100).fill('#1e3a5f');
    doc.fill('#ffffff').fontSize(22).font('Helvetica-Bold')
      .text('IKONEX ACADEMY', 50, 25, { align: 'center' });
    doc.fontSize(12).font('Helvetica')
      .text('Student Report Card', 50, 55, { align: 'center' });
    doc.fontSize(10).text(`Academic Year: ${scores[0]?.academic_year || '2025'} | ${scores[0]?.term || 'Term 1'}`, 50, 75, { align: 'center' });

    // Student Info Box
    doc.fill('#000').rect(50, 115, 495, 80).stroke('#d1d5db');
    doc.fontSize(11).font('Helvetica-Bold').fill('#1e3a5f').text('STUDENT INFORMATION', 65, 125);
    doc.font('Helvetica').fill('#000').fontSize(10);
    doc.text(`Name: ${student.first_name} ${student.last_name}`, 65, 145);
    doc.text(`Admission No: ${student.admission_number}`, 65, 160);
    doc.text(`Class: ${student.stream_name || 'N/A'}`, 300, 145);
    doc.text(`Gender: ${student.gender || 'N/A'}`, 300, 160);

    // Scores Table
    doc.fontSize(11).font('Helvetica-Bold').fill('#1e3a5f').text('ACADEMIC PERFORMANCE', 50, 215);

    const tableTop = 235;
    const cols = { subject: 50, exam: 270, ca: 340, total: 410, grade: 470, remark: 500 };

    // Table header
    doc.rect(50, tableTop, 495, 22).fill('#1e3a5f');
    doc.fill('#fff').fontSize(9).font('Helvetica-Bold');
    doc.text('SUBJECT', cols.subject + 5, tableTop + 7);
    doc.text('EXAM', cols.exam, tableTop + 7);
    doc.text('CA', cols.ca, tableTop + 7);
    doc.text('TOTAL', cols.total, tableTop + 7);
    doc.text('GRADE', cols.grade, tableTop + 7);
    doc.text('REMARK', cols.remark, tableTop + 7);

    // Table rows
    scores.forEach((score, i) => {
      const y = tableTop + 22 + i * 22;
      if (i % 2 === 0) doc.rect(50, y, 495, 22).fill('#f9fafb');
      else doc.rect(50, y, 495, 22).fill('#ffffff');
      doc.fill('#000').fontSize(9).font('Helvetica');
      doc.text(score.subject_name, cols.subject + 5, y + 7, { width: 210 });
      doc.text(String(score.exam_score), cols.exam, y + 7);
      doc.text(String(score.ca_score), cols.ca, y + 7);
      doc.text(String(score.total_score), cols.total, y + 7);
      doc.text(score.grade || '-', cols.grade, y + 7);
      doc.text(score.remark || '-', cols.remark, y + 7);
    });

    // Summary box
    const summaryY = tableTop + 22 + scores.length * 22 + 20;
    doc.rect(50, summaryY, 495, 70).fill('#f0f9ff').stroke('#bfdbfe');
    doc.fill('#1e3a5f').fontSize(11).font('Helvetica-Bold').text('SUMMARY', 65, summaryY + 10);
    doc.fill('#000').fontSize(10).font('Helvetica');
    doc.text(`Total Marks: ${total.toFixed(2)}`, 65, summaryY + 28);
    doc.text(`Average Score: ${average}%`, 65, summaryY + 44);
    doc.text(`Overall Position: #${position}`, 300, summaryY + 28);
    doc.text(`Subjects Sat: ${scores.length}`, 300, summaryY + 44);

    // Footer
    doc.fontSize(8).fill('#6b7280')
      .text('Generated by Ikonex Academy SMS', 50, 760, { align: 'center' });

    doc.end();
  } catch (err) { next(err); }
};

const generateClassReport = async (req, res, next) => {
  try {
    const streamRes = await pool.query('SELECT * FROM streams WHERE id=$1', [req.params.streamId]);
    if (!streamRes.rows.length) return res.status(404).json({ error: 'Stream not found' });
    const stream = streamRes.rows[0];

    const studentsRes = await pool.query(
      'SELECT * FROM students WHERE stream_id=$1 ORDER BY last_name',
      [req.params.streamId]
    );

    const results = await Promise.all(studentsRes.rows.map(async (student) => {
      const scoresRes = await pool.query(`
        SELECT sc.total_score FROM scores sc WHERE sc.student_id = $1
      `, [student.id]);
      const scores = scoresRes.rows;
      const total = scores.reduce((sum, s) => sum + parseFloat(s.total_score), 0);
      const average = scores.length ? (total / scores.length).toFixed(2) : 0;
      return { ...student, total_marks: total.toFixed(2), average, subjects_count: scores.length };
    }));

    results.sort((a, b) => b.total_marks - a.total_marks);
    results.forEach((s, i) => s.position = i + 1);

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=class_report_${stream.name}.pdf`);
    doc.pipe(res);

    // Header
    doc.rect(0, 0, 595, 100).fill('#1e3a5f');
    doc.fill('#ffffff').fontSize(22).font('Helvetica-Bold')
      .text('IKONEX ACADEMY', 50, 25, { align: 'center' });
    doc.fontSize(14).font('Helvetica')
      .text(`Class Performance Report — ${stream.name}`, 50, 58, { align: 'center' });
    doc.fontSize(10).text(`Total Students: ${results.length}`, 50, 78, { align: 'center' });

    // Table
    const tableTop = 120;
    doc.rect(50, tableTop, 495, 22).fill('#1e3a5f');
    doc.fill('#fff').fontSize(9).font('Helvetica-Bold');
    doc.text('POS', 55, tableTop + 7);
    doc.text('NAME', 90, tableTop + 7);
    doc.text('ADMISSION #', 280, tableTop + 7);
    doc.text('TOTAL', 380, tableTop + 7);
    doc.text('AVERAGE', 440, tableTop + 7);

    results.forEach((s, i) => {
      const y = tableTop + 22 + i * 22;
      if (i % 2 === 0) doc.rect(50, y, 495, 22).fill('#f9fafb');
      else doc.rect(50, y, 495, 22).fill('#ffffff');
      doc.fill(i === 0 ? '#d97706' : '#000').fontSize(9).font(i < 3 ? 'Helvetica-Bold' : 'Helvetica');
      doc.text(`#${s.position}`, 55, y + 7);
      doc.fill('#000').text(`${s.first_name} ${s.last_name}`, 90, y + 7, { width: 180 });
      doc.text(s.admission_number, 280, y + 7);
      doc.text(String(s.total_marks), 380, y + 7);
      doc.text(String(s.average), 440, y + 7);
    });

    doc.fontSize(8).fill('#6b7280')
      .text('Generated by Ikonex Academy SMS', 50, 760, { align: 'center' });

    doc.end();
  } catch (err) { next(err); }
};

module.exports = { generateStudentReportCard, generateClassReport };